### ISSUE TITLE
Import does not seem to work on mobile devices

### ISSUE THREAD

**Issue by PunchboxNET** [eguneys/aidchess24#2]
The import feature does not work on mobile devices, posting a link and tapping import does not do anything.

**Comment by eguneys** [comment]
I could successfully imported on my mobile device. Could you share your study link, maybe it's private. And please try again in a PC. Also could you share the model of your device.

**Comment by PunchboxNET** [comment]
https://lichess.org/study/rvWOdIf9 it is public it does not work

**Comment by eguneys** [comment]
> Sharing and exporting were disabled by the study owner.

They don't share the study even though study is available on lichess, you can't download the PGN or fetch the study from lichess api, which is what I was doing.

Currently these studies doesn't follow the format, and I don't always prefer the lines as good quality. I plan to clone them with the owner's permission and share them publicly with the proper format and sections, and feature them on the website or somewhere.

But if you want to follow up hit this discord for more information https://discord.gg/k3BfKPcd

**Comment by eguneys** [comment]
Oh, I also added an import option to paste the study PGN, instead of lichess study link, so if you have the study PGN from somewhere else you can do that.

**Comment by PunchboxNET** [comment]
Ok, thanks. That should help.On May 19, 2024, at 18:10, eguneys ***@***.***> wrote:﻿
Oh, I also added an import option to paste the study PGN, instead of lichess study link, so if you have the study PGN from somewhere else you can do that.
